// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA52EJOm_9jwhl9lilHgaRTjd4RxzPOeyw',
    appId: '1:264697540507:web:0d223a9f936ec7de1fbb3e',
    messagingSenderId: '264697540507',
    projectId: 'ks-kalender-app',
    authDomain: 'ks-kalender-app.firebaseapp.com',
    databaseURL: 'https://ks-kalender-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ks-kalender-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdUyYPUNXyqJNLB6Wtu1xsf8KnL_kjXXQ',
    appId: '1:264697540507:android:d510b8c705ab0f2a1fbb3e',
    messagingSenderId: '264697540507',
    projectId: 'ks-kalender-app',
    databaseURL: 'https://ks-kalender-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ks-kalender-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzzD4VmZwpmIW1iCe2RQa6UXngGpKQOEs',
    appId: '1:264697540507:ios:f14e76a518e779fc1fbb3e',
    messagingSenderId: '264697540507',
    projectId: 'ks-kalender-app',
    databaseURL: 'https://ks-kalender-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ks-kalender-app.firebasestorage.app',
    iosBundleId: 'com.example.databaseTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzzD4VmZwpmIW1iCe2RQa6UXngGpKQOEs',
    appId: '1:264697540507:ios:f14e76a518e779fc1fbb3e',
    messagingSenderId: '264697540507',
    projectId: 'ks-kalender-app',
    databaseURL: 'https://ks-kalender-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ks-kalender-app.firebasestorage.app',
    iosBundleId: 'com.example.databaseTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA52EJOm_9jwhl9lilHgaRTjd4RxzPOeyw',
    appId: '1:264697540507:web:f2ea925cd55cbab91fbb3e',
    messagingSenderId: '264697540507',
    projectId: 'ks-kalender-app',
    authDomain: 'ks-kalender-app.firebaseapp.com',
    databaseURL: 'https://ks-kalender-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ks-kalender-app.firebasestorage.app',
  );
}
